openapi: 3.0.3
info:
  title: 'Abyss Tracker Conduit'
  description: 'An API interface for the Abyss Tracker'
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/conduit/v1/fits/list:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  error: 'Please provide a valid authentication bearer token.'
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: 'Please provide a valid authentication bearer token.'
      tags:
        - Endpoints
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
