<?php
    return
        ['names' => ['Abdel Rahman Badawi',
     'Ackermann',
     'Adrianopole',
     'Africanus',
     'Agatha King',
     'Alastair Rauch',
     'Ambedkar',
     'Amberjack',
     'Amun-Ra',
     'Amun-Ra-class',
     'Amunet',
     'Ando',
     'Andreas Hofer',
     'Anubis',
     'Apalala',
     'Apophis',
     'Arboghast',
     'Arcadia Rose',
     'Aristophanes',
     'Armstrong',
     'Aryabhata',
     'Askia',
     'Assurance of Peace',
     'August Marchant',
     'Augustin Gamarra',
     'Avalanche',
     'Azure Dragon',
     'Badass Motherfucker',
     'Bandon',
     'Barbapiccola',
     'Barbatana de Tubarao',
     'Barkeith',
     'Battle Angel',
     'Category:Battleship',
     'Bedayadat Jadida',
     'Bellaire',
     'Bellerophon',
     'Belt Transit Ferry',
     'Benedict',
     'Bernadette Koe',
     'Bethany Thomas',
     'Bhikaji Cama',
     'Blasphemous Jester',
     'Blue Genius',
     'Brilliant Iris',
     'Callisto\'s Dream',
'Campsi',
'Canterbury',
'Carcassonne',
'Carson Lei',
'Casa Azul',
'Caspian',
'Cassandra',
'Cassius',
'Cavalier',
'Cerisier',
'Charles Lyell',
'Chet Lam',
'Chetzemoka',
'Cleo',
'Connaught',
'Countee Cullen',
'Cydonia',
'Cú Chulainn',
'Dagmar',
'Dagny Taggart',
'Dagon',
'Damascus',
'Darius',
'Daskell',
'Deliverance',
'Donnager',
'Drybeck',
'Dyson',
'Edward Carr',
'Edward Israel',
'Ekandjo',
'Eye of the Typhoon',
'Falcon',
'Feodorovna',
'Finland',
'Firebrand',
'Frank Aiken',
'Frederick Lewis',
'Garcia y Vazquez',
'Gathering Storm',
'Giambattista',
'Governor Knight',
'Gozerian',
'Greenville',
'Guanshiyin',
'Guard of Passage',
'Guy Molinari',
'Halpenny',
'Hamill-Stewart',
'Hammurabi',
'Han Yu',
'Harman Dae-Jung',
'Harmony',
'Hathor',
'Heart of the Tempest',
'Heavy-G',
'Heisserer',
'Highland Swing',
'Hijo de puta',
'Hodson',
'Hornblower',
'Horus',
'Hotspur',
'Iani Chaos',
'Icaria Planum',
'Iceni',
'Independence',
'Jaquenetta',
'Jefferson Mays',
'Jimenez',
'Karakum',
'Kennedy',
'Khonsu-class',
'Kingfisher',
'Kittur Chennamma',
'Knight',
'Koto',
'Lazy Songbird',
'Leonidas',
'Lightbreaker',
'Lucien',
'Macedon',
'Malaclypse',
'Mammatus',
'Marasmus',
'Marco Pursuit',
'Mark Watney',
'McCabe',
'Michael Souther',
'Mikhaylov',
'Minsky',
'Mograph',
'Monsoon',
'Morrigan',
'Mosley',
'Mouse Pie',
'Munroe-class',
'Mustang Sally',
'Nang Kwak',
'Nathan Hale',
'Nauvoo',
'Nephthys',
'Neve Avivim',
'Notus',
'Odachi',
'Okavango',
'Okimbo',
'Old Buncome',
'Oleander-Swift',
'One Hit Wonder',
'Ontario',
'Orinoco',
'Osiris',
'Panshin',
'Pau Kant',
'Achaz',
'Alarei',
'AML Demeter',
'Arcturian Jade',
'Audacity',
'Azedes',
'Borealis',
'Boundless',
'Chayym',
'Cybaen',
'Cyniad',
'Decimation',
'Defrahnz',
'Derelict Reaper',
'Destiny Ascension',
'Elbrus',
'ESAV Majriti',
'Excelsior',
'Fusion',
'Galduu',
'Ghrigult',
'Glory of Khar\'shan',
'Grande Mar',
'Harbinger',
'Helash',
'Honorata',
'Ibn Battuta',
'Idenna',
'Iktomi',
'Indomitable',
'Kalanhai',
'Kara',
'Keelah Si\'yah',
'Konesh',
'Kupe',
'Kwunu',
'Leusinia',
'Leviathan of Dis',
'Moreh',
'MSV Adams',
'MSV Anixara',
'MSV Atlanta',
'MSV Broken Arrow',
'MSV Collins',
'MSV Cornucopia',
'MSV Corsica',
'MSV Estevanico',
'MSV Fedele',
'MSV Hugo Gernsback',
'MSV Icarus',
'MSV Kent',
'MSV Kirkwall',
'MSV Majesty',
'MSV Monarch',
'MSV Ontario',
'MSV Rosalie',
'MSV Sevrum',
'MSV Stanislaw',
'MSV Strontium Mule',
'MSV Wallace',
'MSV Worthington',
'Nalotir',
'Natanus',
'Neema',
'Nefrane',
'Nexus',
'Niqunus',
'Normandy',
'Novarra',
'Ostral',
'Paarchero',
'Pallu\'Kaziel',
'Penumbra Apex',
'Periphona',
'PFS Havincaw',
'Prometheus Station',
'Qwib-Qwib',
'Rayya',
'Regarikas III',
'Resolute',
'Sacred Angel',
'Selani',
'Shellen',
'SSV Aconcagua',
'SSV Agincourt',
'SSV Ain Jalut',
'SSV Benjamin Davis',
'SSV Budapest',
'SSV Cairo',
'SSV Cape Town',
'SSV Einstein',
'SSV Elbrus',
'SSV Emden',
'SSV Everest',
'SSV Fuji',
'SSV Geneva',
'SSV Hastings',
'SSV Hawking',
'SSV Hong Kong',
'SSV Hyderabad',
'SSV Iwo Jima',
'SSV Jakarta',
'SSV Kilimanjaro',
'SSV Leipzig',
'SSV Logan',
'SSV London',
'SSV Madrid',
'SSV Manila',
'SSV Nairobi',
'SSV New Delhi',
'SSV Normandy SR-1',
'SSV Orizaba',
'SSV Perugia',
'SSV Seoul',
'SSV Shanghai',
'SSV Shasta',
'SSV Shenyang',
'SSV Tai Shan',
'SSV Tokyo',
'SSV Trafalgar',
'SSV Warsaw',
'SSV Zama',
'Tavura\'s Gain',
'Ter Alan',
'Tesleya',
'THV Ravuna',
'Tonbay',
'Tunerron',
'Typhoon',
'Ulnay',
'Undaunted',
'Usela',
'Verakan',
'Verallas',
'Verrikan',
'Viridian Zenith',
'Warsaw',
'Yaska',
'Farre',
'Fortunate',
'Gentle Star',
'Yes, Sir, That’s My Baby',
'Tell me Another One',
'No, Sir, I Don’t Mean Maybe ',
'I\'ll always remember you like a child']
        ];
