on: 
  push:
    branches: prod
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: Composer Action
      uses: MilesChou/composer-action@v1.0.2
      run: install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
  
    - name: Use Node.js 14
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run prod
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
